### PR TITLE
Group traits that are mutually exclusive together

### PR DESCRIPTION
**Pull request by winglian**
This way, the same cattribute always appears in the same position across all the windows and is also lined up with any other cattribute for the gene that encodes it.

### CODE REVIEW

**Comment by HaJaeKyung** [comment]
This looks nice. How is the order determined? And have you factored in unseen attributes and cats with more than 8 attributes? https://www.cryptokitties.co/profile/0x221f890d45213b100c90f50a4509943156ecbff5

**Comment by winglian** [comment]
The order is basically grouped by traits from data I've compiled from cryptokittydex. As for unseen attributes, that's going to have to be manual for now.  As for kitties with more than 8 attributes, I didn't realize until you pointed it out that that was possible.

**Comment by HaJaeKyung** [comment]
@winglian here is a way to get the type of each attribute. Should make it pretty easy now.
https://api.cryptokitties.co/cattributes?type=true

**Comment by winglian** [comment]
@HaJaeKyung thanks, updated to use that endpoint

**Pull request merged**
