### PR TITLE
Adding 2 tools sites

### PR DESCRIPTION
**Pull request by doeiqts**
Adding basic support for kittytools.herokuapp.com and
kittygenerations.herokuapp.com

### CODE REVIEW

**Comment by HaJaeKyung** [comment]
I tested it and works ok but it gives some errors on the third party sites.

**Comment by doeiqts** [comment]
Can you let me know what those errors are? I didn't see any errors on the pages, but maybe I just didn't notice them.

**Comment by HaJaeKyung** [comment]
Kitties with bun in oven or resting give a textContent undefined error

**Comment by doeiqts** [comment]
Ah, from the console. My apologizes, I was just looking at the page output to see whether it was able to show the data I was wanting, wasn't actually looking at what else happened behind the scenes. I'll investigate and see if I can exclude other mainsite features from the extra sites.

**Comment by HaJaeKyung** [comment]
Good job

**Pull request merged**
